name: 下载hf模型，上传到docker hub

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check
        run: |
          echo "Free space:"
          df -h
      - name: 下载hf模型
        run: |
          git lfs install
          git clone https://oauth2:${{ secrets.MODEL_SCOPE_GIT_TOKEN }}@www.modelscope.cn/Poikid/Qwen2.5-32B-AGI-Q4_K_M-GGUF.git
          cd Qwen2.5-32B-AGI-Q4_K_M-GGUF
          ls -l
          pip install "huggingface_hub[hf_transfer]"
          huggingface-cli download Karsh-CAI/Qwen2.5-32B-AGI-Q4_K_M-GGUF --local-dir ./models
