name: 下载hf模型，上传到docker hub

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check
        run: |
          echo "Free space:"
          df -h
      - name: 下载hf模型
        run: |
          git config --global user.email $GIT_EMAIL
          git config --global user.name $GIT_USER
          git lfs install
          echo "https://oauth2:${{ secrets.MODEL_SCOPE_GIT_TOKEN }}@www.modelscope.cn/$MS_USER/$MODEL_NAME.git"
          git clone https://oauth2:${{ secrets.MODEL_SCOPE_GIT_TOKEN }}@www.modelscope.cn/$MS_USER/$MODEL_NAME.git
          echo "modelscope克隆成功"

          cd Qwen2.5-32B-AGI-Q4_K_M-GGUF
          pip install "huggingface_hub[hf_transfer]"
          echo "安装huggingface-cli成功"

          huggingface-cli download $MODEL_NAME --local-dir ./
          echo "下载huggingface模型成功"

          echo "modelscope目录"
          ls -l

          git add .
          git commit -m "上传模型"
          echo "modelscope提交成功"

          git push
          echo "modelscope推送成功"

        env:
          GIT_USER: mutemoon
          GIT_EMAIL: 1036066414@qq.com
          # MODEL_NAME: Qwen2.5-32B-AGI-Q4_K_M-GGUF
          # HF_USER: Karsh-CAI
          MODEL_NAME: Qwen2.5-0.5B
          HF_USER: Qwen
          MS_USER: Poikid
