name: 下载hf模型，上传到docker hub

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check
        run: |
          echo "Free space:"
          df -h
      - name: 下载hf模型
        run: |
          pip install "huggingface_hub[hf_transfer]"
          huggingface-cli download Karsh-CAI/Qwen2.5-32B-AGI-Q4_K_M-GGUF
